<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
<?php
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
?>

    
	<style>
		body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
		table.list {width:100%}
		table.list tr td {border-bottom: 1px solid #F5F5F5; text-align: center}
		table.list tbody tr:hover {background: #F5F5F5}
	</style>
</head>
<body style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
	<div style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
		<?php echo $this->content; ?>
	</div>
</body>
</html>